name: run-unit-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #- name: Install gtest manually
    #  run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: make
      run: cd build && make
    - name: Run Tests
      run: |
       ${{github.workspace}}/build/tests/CBUSCircularBuffertest
       ${{github.workspace}}/build/tests/CBUSConfigtest
       ${{github.workspace}}/build/tests/CBUSLEDtest
       ${{github.workspace}}/build/tests/CBUSLongMessagetest
       ${{github.workspace}}/build/tests/CBUSParamstest
       ${{github.workspace}}/build/tests/CBUSSwitchtest
       ${{github.workspace}}/build/tests/CBUStest
    - name: Check Test Coverage
      uses: threeal/gcovr-action@v1.1.0
      with:
         root: ${{github.workspace}}
         excludes: |
            '${{github.workspace}}/build/*'
            '${{github.workspace}}/tests/*'
         html-out: coverage.html
         html-title: CBUSPicoLib Test Coverage Report
    - name: Create a temporary artifact folder
      working-directory: ${{github.workspace}}
      run: mkdir downloads
    - name: Add artifacts to publish
      run: |
         cd downloads
         cp ${{github.workspace}}/coverage.html .
         cd ..
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with: 
         name: coverage-report
         path: downloads/
